export const UPLOAD_FILE = "UPLOAD_FILE";
export const UPLOAD_MOCK = "UPLOAD_MOCK";

export const DELETE_TRANSACTION_SUCCESS = "DELETE_TRANSACTION_SUCCESS";
export const DELETE_TRANSACTION_CANCEL = "DELETE_TRANSACTION_CANCEL";

export const SAVE_TRANSACTION_CHANGES = "SAVE_TRANSACTION_CHANGES";

export const MENU_STATUS_FILTER = "MENU_STATUS_FILTER";
export const MENU_TYPE_FILTER = "MENU_TYPE_FILTER";
export const MENU_FILTER = "MENU_FILTER";

export const PAGINATION_CURRENT_PAGE = "PAGINATION_CURRENT_PAGE";
export const PAGINATION_PAGE_SIZE = "PAGINATION_PAGE_SIZE";

export const MODAL_OPEN = "MODAL_OPEN";
export const MODAL_CLOSE = "MODAL_CLOSE";
export const MODAL_OPTION = "MODAL_OPTION";
